<a href="https://colab.research.google.com/github/abbudjoe/lectures/blob/codex%2Fcourse-work/course-work/notebooks/lesson_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/abbudjoe/lectures/blob/codex/course-work/notebooks/lesson_01.ipynb" target="_parent">  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 01

Use this notebook for scratch work while reading through `lecture_01.py` and the course materials.

I'll guide you through the ideas and code in the Codex thread while you do the thinking and experimentation here.

In [1]:
# Optional setup for a fresh Colab runtime.
# Run this once if you want local copies of the course repo and its Python dependencies.
# This repo is a collection of lecture scripts, so we install dependencies directly
# instead of trying to editable-install the repo itself.

from pathlib import Path

repo = Path('/content/lectures')
if not repo.exists():
    !git clone https://github.com/abbudjoe/lectures.git /content/lectures

%cd /content/lectures
!git fetch origin
!git checkout codex/course-work
!pip install -q 'edtrace>=0.1.12' 'einops>=0.8.2' 'modal>=1.4.1' 'tiktoken>=0.12.0'

Cloning into '/content/lectures'...
remote: Enumerating objects: 1426, done.
remote: Counting objects: 100% (633/633), done.
remote: Compressing objects: 100% (270/270), done.
remote: Total 1426 (delta 393), reused 360 (delta 343), pack-reused 793 (from 2)
Receiving objects: 100% (1426/1426), 136.47 MiB | 24.68 MiB/s, done.
Resolving deltas: 100% (737/737), done.
/content/lectures
Branch 'codex/course-work' set up to track remote branch 'codex/course-work' from 'origin'.
Switched to a new branch 'codex/course-work'
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 826.2/826.2 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 467.3/467.3 kB 24.6 MB/s eta 0:00:00


In [2]:
from pathlib import Path

repo = Path("/content/assignment1-basics")

if not repo.exists():
    !git clone https://github.com/abbudjoe/assignment1-basics.git /content/assignment1-basics

%cd /content/assignment1-basics
!git fetch origin
!git switch codex/tokenizer-wip
!git pull
!pip install -q uv
!uv sync

Cloning into '/content/assignment1-basics'...
remote: Enumerating objects: 395, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 395 (delta 45), reused 26 (delta 26), pack-reused 346 (from 3)
Receiving objects: 100% (395/395), 14.25 MiB | 23.50 MiB/s, done.
Resolving deltas: 100% (214/214), done.
/content/assignment1-basics
Branch 'codex/tokenizer-wip' set up to track remote branch 'codex/tokenizer-wip' from 'origin'.
Switched to a new branch 'codex/tokenizer-wip'
Already up to date.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.4/24.4 MB 59.2 MB/s eta 0:00:00
Using CPython 3.12.13 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
Resolved 67 packages in 1ms
Prepared 66 packages in 1m 10s
Installed 66 packages in 958ms
 + annotated-types==0.7.0
 + certifi==2026.2.25
 + charset-normalizer==3.4.6
 + click==8.3.1
 + cs336-basics==26.0.0 (from file:///content/assignment1-basics)
 + cuda-bindings==13.2.

In [40]:
# Commit/Push updated code
from google.colab import userdata
import os

os.environ["GITHUB_TOKEN"] = userdata.get("GITHUB_TOKEN")
!git config user.name "abbudjoe"
!git config user.email "abbudjoe@gmail.com"
!git add cs336_basics/model.py
!git add tests/adapters.py
!git commit -m "Implement TransformerLM"
!git push https://x-access-token:${GITHUB_TOKEN}@github.com/abbudjoe/assignment1-basics.git codex/tokenizer-wip
!git status
!git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/abbudjoe/assignment1-basics.git
!git push -u origin codex/tokenizer-wip
!git status


[codex/tokenizer-wip e21c03a] Implement TransformerLM
 2 files changed, 48 insertions(+), 1 deletion(-)
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 941 bytes | 941.00 KiB/s, done.
Total 6 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/abbudjoe/assignment1-basics.git
   11165d2..e21c03a  codex/tokenizer-wip -> codex/tokenizer-wip
On branch codex/tokenizer-wip
Your branch is ahead of 'origin/codex/tokenizer-wip' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
Branch 'codex/tokenizer-wip' set up to track remote branch 'codex/tokenizer-wip' from 'origin'.
Everything up-to-date
On branch codex/tokenizer-wip
Your branch is up to date with 'origin/codex/tokenizer-wip'.

nothing to commit, working tree clean


In [4]:
# !git checkout codex/tokenizer-wip
!git status

On branch codex/tokenizer-wip
Your branch is up to date with 'origin/codex/tokenizer-wip'.

nothing to commit, working tree clean


In [5]:
import sys
import importlib

repo_root = "/content/assignment1-basics"
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

import cs336_basics.tokenizer as tok
importlib.reload(tok)

dir(tok)

# tokenizer = tok.get_tokenizer({0: b"h", 1: b"i"}, [])
# print(tokenizer.decode([0, 1]))

# tokenizer = tok.get_tokenizer({0: "é".encode("utf-8")}, [])
# print(tokenizer.decode([0]))

# !uv run pytest tests/test_tokenizer.py::test_roundtrip_empty -q
# !uv run pytest tests/test_tokenizer.py::test_roundtrip_single_character -q
# !uv run pytest tests/test_tokenizer.py -q

# !uv run pytest tests/test_tokenizer.py tests/test_train_bpe.py -q

!uv run pytest tests/test_train_bpe.py::test_train_bpe -q



tests/test_train_bpe.py::test_train_bpe PASSED

============================== 1 passed in 1.02s ===============================


In [6]:
from pathlib import Path
from cs336_basics.tokenizer import (
    text_to_byte_sequences,
    build_pair_index,
    apply_merge_with_index,
)

input_path = Path("tests/fixtures/corpus.en")
text = input_path.read_text(encoding="utf-8")

corpus = text_to_byte_sequences(text, ["<|endoftext|>"])
pair_counts, pair_to_sequences = build_pair_index(corpus)

best_pair = max(pair_counts, key=lambda pair: (pair_counts[pair], pair))
print("first best:", best_pair, pair_counts[best_pair])

apply_merge_with_index(corpus, pair_counts, pair_to_sequences, best_pair)

print("after merge count:", pair_counts.get(best_pair))
print("after merge indexed sequences:", len(pair_to_sequences.get(best_pair, set())))

second_pair = max(pair_counts, key=lambda pair: (pair_counts[pair], pair))
print("second best:", second_pair, pair_counts[second_pair])



first best: (b' ', b't') 2940
after merge count: None
after merge indexed sequences: 0
second best: (b' ', b'a') 2214


In [7]:
import torch
torch.set_printoptions(precision=3, sci_mode=False)

In [8]:
# Three token vectors.
# Think: token 0, token 1, token 2.
# Each token has d_model = 3 features.

x = torch.tensor([
    [1.0, 0.0, 0.5],
    [0.0, 1.0, -0.5],
    [1.0, 1.0, 0.25],
])

print("x: ")
print(x)
print("x shape: ", x.shape)

x: 
tensor([[ 1.000,  0.000,  0.500],
        [ 0.000,  1.000, -0.500],
        [ 1.000,  1.000,  0.250]])
x shape:  torch.Size([3, 3])


In [9]:
# W_q has shape [d_k, d_model].
# Here d_k = 2 and d_model = 3.
# So W_q is [2, 3].

W_q = torch.tensor([
    [0.8, 0.2, -0.1],
    [0.1, 0.9, 0.3],
])

print("W_q:")
print(W_q)
print("W_q shape:", W_q.shape)

print("\nW_q.T:")
print(W_q.T)
print("W_q.T shape:", W_q.T.shape)

W_q:
tensor([[ 0.800,  0.200, -0.100],
        [ 0.100,  0.900,  0.300]])
W_q shape: torch.Size([2, 3])

W_q.T:
tensor([[ 0.800,  0.100],
        [ 0.200,  0.900],
        [-0.100,  0.300]])
W_q.T shape: torch.Size([3, 2])


In [10]:
Q = x @ W_q.T

print("Q = x @ W_q.T")
print(Q)
print("Q shape:", Q.shape)

Q = x @ W_q.T
tensor([[0.750, 0.250],
        [0.250, 0.750],
        [0.975, 1.075]])
Q shape: torch.Size([3, 2])


In [11]:
manual_q00 = (
    x[0, 0] * W_q.T[0, 0]
    + x[0, 1] * W_q.T[1, 0]
    + x[0, 2] * W_q.T[2, 0]
)

print("manual Q[0, 0]:", manual_q00)
print("torch Q[0, 0]:", Q[0, 0])

manual Q[0, 0]: tensor(0.750)
torch Q[0, 0]: tensor(0.750)


In [12]:
print("x row 0:", x[0])
print("\nW_q.T column 0:", W_q.T[:, 0])

x row 0: tensor([1.000, 0.000, 0.500])

W_q.T column 0: tensor([ 0.800,  0.200, -0.100])


In [13]:
W_k = torch.tensor([
    [0.7, 0.3, 0.2],
    [0.4, 0.6, -0.2],
])

W_v = torch.tensor([
    [1.0, -0.3, 0.4],
    [0.2, 0.8, -0.1],
])

K = x @ W_k.T
V = x @ W_v.T

print("K = x @ W_k.T:")
print(K)
print("K shape:", K.shape)

print("\nV = x @ W_v.T:")
print(V)
print("V shape:", V.shape)

K = x @ W_k.T:
tensor([[0.800, 0.300],
        [0.200, 0.700],
        [1.050, 0.950]])
K shape: torch.Size([3, 2])

V = x @ W_v.T:
tensor([[ 1.200,  0.150],
        [-0.500,  0.850],
        [ 0.800,  0.975]])
V shape: torch.Size([3, 2])


In [14]:
scores = Q @ K.T

print("K.T:")
print(K.T)
print("K.T shape:", K.T.shape)

print("\nscores = Q @ K.T:")
print(scores)
print("scores shape:", scores.shape)

K.T:
tensor([[0.800, 0.200, 1.050],
        [0.300, 0.700, 0.950]])
K.T shape: torch.Size([2, 3])

scores = Q @ K.T:
tensor([[0.675, 0.325, 1.025],
        [0.425, 0.575, 0.975],
        [1.103, 0.948, 2.045]])
scores shape: torch.Size([3, 3])


In [15]:
manual_score_02 = (
    Q[0, 0] * K.T[0, 2]
    + Q[0, 1] * K.T[1, 2]
)

print("manual scores[0, 2]:", manual_score_02)
print("torch  scores[0, 2]:", scores[0, 2])

print("\nQ row 0:")
print(Q[0])

print("\nK.T column 2, which is K row 2:")
print(K.T[:, 2])
print(K[2])


manual scores[0, 2]: tensor(1.025)
torch  scores[0, 2]: tensor(1.025)

Q row 0:
tensor([0.750, 0.250])

K.T column 2, which is K row 2:
tensor([1.050, 0.950])
tensor([1.050, 0.950])


In [16]:
import torch
torch.set_printoptions(precision=3, sci_mode=False)

# Pretend this is x_1 after attention + residual.
# 2 tokens, d_model = 2
x_1 = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0],
])

print("x_1:")
print(x_1)
print("shape:", x_1.shape)


x_1:
tensor([[1., 2.],
        [3., 4.]])
shape: torch.Size([2, 2])


In [17]:
W_up = torch.tensor([
    [1.0, 0.0],
    [0.0, 1.0],
    [1.0, 1.0],
])

up = x_1 @ W_up.T
print("W_up:")
print(W_up)
print("W_up.T:")
print(W_up.T)

print("\nup = x_1 @ W_up.T:")
print(up)
print("up shape:", up.shape)

W_up:
tensor([[1., 0.],
        [0., 1.],
        [1., 1.]])
W_up.T:
tensor([[1., 0., 1.],
        [0., 1., 1.]])

up = x_1 @ W_up.T:
tensor([[1., 2., 3.],
        [3., 4., 7.]])
up shape: torch.Size([2, 3])


In [18]:
W_gate = torch.tensor([
    [ 1.0, -1.0],
    [ 0.5,  0.5],
    [-1.0,  1.0],
])

gate = x_1 @ W_gate.T

print("W_gate:")
print(W_gate)
print("W_gate.T:")
print(W_gate.T)

print("\ngate = x_1 @ W_gate.T:")
print(gate)
print("gate shape:", gate.shape)

W_gate:
tensor([[ 1.000, -1.000],
        [ 0.500,  0.500],
        [-1.000,  1.000]])
W_gate.T:
tensor([[ 1.000,  0.500, -1.000],
        [-1.000,  0.500,  1.000]])

gate = x_1 @ W_gate.T:
tensor([[-1.000,  1.500,  1.000],
        [-1.000,  3.500,  1.000]])
gate shape: torch.Size([2, 3])


In [19]:
gate_activated = torch.nn.functional.silu(gate)

("gate_activated = silu(gate):")
print(gate_activated)
print("gate_activated shape:", gate_activated.shape)

tensor([[-0.269,  1.226,  0.731],
        [-0.269,  3.397,  0.731]])
gate_activated shape: torch.Size([2, 3])


In [20]:
hidden = gate_activated * up

print("up:")
print(up)

print("\ngate_activated:")
print(gate_activated)

print("\nhidden = gate_activated * up:")
print(hidden)
print("hidden shape:", hidden.shape)

up:
tensor([[1., 2., 3.],
        [3., 4., 7.]])

gate_activated:
tensor([[-0.269,  1.226,  0.731],
        [-0.269,  3.397,  0.731]])

hidden = gate_activated * up:
tensor([[-0.269,  2.453,  2.193],
        [-0.807, 13.590,  5.117]])
hidden shape: torch.Size([2, 3])


In [21]:
W_down = torch.tensor([
    [1.0, 0.0, 0.5],
    [0.0, 1.0, -0.5],
])

mlp_update = hidden @ W_down.T

print("W_down:")
print(W_down)
print("W_down.T:")
print(W_down.T)

print("\nmlp_update = hidden @ W_down.T:")
print(mlp_update)
print("mlp_update shape:", mlp_update.shape)

W_down:
tensor([[ 1.000,  0.000,  0.500],
        [ 0.000,  1.000, -0.500]])
W_down.T:
tensor([[ 1.000,  0.000],
        [ 0.000,  1.000],
        [ 0.500, -0.500]])

mlp_update = hidden @ W_down.T:
tensor([[ 0.828,  1.356],
        [ 1.752, 11.031]])
mlp_update shape: torch.Size([2, 2])


In [22]:

%cd /content/assignment1-basics/
!uv run pytest tests/test_model.py::test_embedding -q

/content/assignment1-basics

tests/test_model.py::test_embedding PASSED

============================== 1 passed in 0.12s ===============================


In [35]:
import json
import torch
from pathlib import Path

FIXTURES_PATH = Path("tests/fixtures")

state_dict = torch.load(
    FIXTURES_PATH / "ts_tests" / "model.pt",
    map_location="cpu",
)

config = json.load(open(FIXTURES_PATH / "ts_tests" / "model_config.json"))

state_dict = {k.replace("_orig_mod.", ""): v for k, v in state_dict.items()}

ts_state_dict = (state_dict, config)
block_weights = {
    k.replace("layers.0.", ""): v
    for k, v in state_dict.items()
    if "layers.0." in k
}

print(block_weights.keys())
print(config)

for key in state_dict.keys():
    print(key)


dict_keys(['attn.q_proj.weight', 'attn.k_proj.weight', 'attn.v_proj.weight', 'attn.output_proj.weight', 'ffn.w1.weight', 'ffn.w2.weight', 'ffn.w3.weight', 'ln1.weight', 'ln2.weight'])
{'vocab_size': 10000, 'context_length': 16, 'd_model': 64, 'num_layers': 3, 'num_heads': 4, 'd_ff': 128, 'remove_rmsnorm': False, 'use_post_norm': False, 'remove_rope': False, 'rope_theta': 10000.0, 'ffn_type': None}
token_embeddings.weight
layers.0.attn.q_proj.weight
layers.0.attn.k_proj.weight
layers.0.attn.v_proj.weight
layers.0.attn.output_proj.weight
layers.0.ffn.w1.weight
layers.0.ffn.w2.weight
layers.0.ffn.w3.weight
layers.0.ln1.weight
layers.0.ln2.weight
layers.1.attn.q_proj.weight
layers.1.attn.k_proj.weight
layers.1.attn.v_proj.weight
layers.1.attn.output_proj.weight
layers.1.ffn.w1.weight
layers.1.ffn.w2.weight
layers.1.ffn.w3.weight
layers.1.ln1.weight
layers.1.ln2.weight
layers.2.attn.q_proj.weight
layers.2.attn.k_proj.weight
layers.2.attn.v_proj.weight
layers.2.attn.output_proj.weight
layers

In [39]:
%cd /content/assignment1-basics/
!uv run pytest tests/test_model.py::test_transformer_block -q
!uv run pytest tests/test_model.py::test_transformer_lm -q

/content/assignment1-basics

tests/test_model.py::test_transformer_block PASSED

============================== 1 passed in 0.05s ===============================

tests/test_model.py::test_transformer_lm PASSED

============================== 1 passed in 0.08s ===============================
